language: python
python:
- '2.7'
- '3.4'
addons:
  apt:
    packages:
    - libzmq3
    - libzmq3-dev
before_install:
- pip install -r requirements.txt
- pip install -r requirements-test.txt
- pip install coveralls
install:
- python setup.py install
script:
- py.test
after_success:
- if [[ $TRAVIS_PYTHON_VERSION == "3.4" ]]; then coveralls; fi
before_deploy:
- pip install twine
deploy:
- provider: pypi
  user: andsor
  password:
    secure: kCUrrvDsflZPl/rBqCvYcJSD0+PVDnkfWww35/8euM4SWen8YGLsyYRqc5cDPYCMOafGquSHoJFuXOEjDC1OKajfeuULsZcFS5FXfV7HuCAKoApCyvkIWt9NJp3zNdrwHOuVsRFFWpaRQ8TC4Er4sf3aBtCJV5BW/8j7DA0D/Uq5Tv9YIm17q/l4P0ag5nhNzTdstaa5Wp/TFSWp5zXlBJx6f2ECzVmIv3XpmhLVotapdwVgUFi5YRpmZV9ShPd8c4Hc1Y8o90DIWMVCOObmPXi2GpaSwumUEMk7XPA36JS/46mVC7j56ifQ4ZkcSJBPhOPCdravsSa/zQpB0Vc0SPzLx0fhYDIttYKDxVptxJc5s0oGBP576mTFGX14NZIHF61s/9k0oHi2umZWwHPrGKxDWb+M6MYKmoulHOOLE02sE7duM6f1AdPqbxR5hVOnMH1aTkvs+57EcsO+gAo7f4+87XBuNvwkeByR0ATc408NNx/qsLv2LOXKMJLcVTS7NgNcx2kBLpUUb/wFn3x7zJlOpN7z2YMuSlrj48/7okumpnzJeC42+n8+HR00ghsoYJuaCpyTG69aOp0z1S+DU/k5hfK3NqPin4J2eY2jAT99u7GpRI4r2bsrWU0AJHUj+NCtdswsLP+raRQn8K6cGA78DEDKRUo5z6xuKSCOOAc=
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: andsor/gridjug
    python: 3.4
    branch: master
- provider: releases
  api_key:
    secure: IctzroDi7ReHR3gHJ+QBqjQCYmiMxVI7F5miVsmL7u/RdR0qf+FY+Q451kxYNZ4D8A0qtVW2dKaatXVnkX+1KftRq0CWPa0q1OIBj/QmhKFaE1VEBnhFreQ4yIqW4vnMY9ei2xilebvm8+8h7iZAf5CsU8Ou0o9fIMF9yuio602OtVbuCjqhTZRKQxd2RkVpqWJeuvjXnkX75ZzVbhKGD38gXkrxlJSZUnHhQOwJ1cmepHIE6mXFj+27zq4Y+bg9duExXyfqdkUAmkPF3L46RVA3p7AvheXsV+CGgijKYnao5I2ZdvVqfhBE1ENGBy+QdGAXH8PLM63fpn4aSO8j92viLirmtZ+9yynlPuoTj9+d5FWe7hl2NNB4PSn3mBwa5oUhMDHjWKy6xDSySq+Pqx2OgiPTX7k6lwXpFi0s/IGF+hHMrJwjKP8MrAWtxFmarsdu1jqYaWTswLJe0KpFrNxAEZzvI5yqh5UEItCtpZ70X3ysK1wepvKmRFJI1ZSVNJtPpSrhaby+sIfTh7biZ3Je9Gss5h6w0E3vpNOEik0AwE5FQj9ud6Nkk03BOJXrQYahanfD492u75EIwhgSyTcuzhCXeaL5YL+HYCv1FOwJBWCXsWtZaUOw5Q8N/XZosOhfzc/tz45LIm/LxcAHsUfjOq4NU05WqVQzkr8jZE8=
  on:
    tags: true
    python: 3.4
    branch: master
