language: python
python:
- '2.7'
- '3.4'
addons:
  apt:
    packages:
    - libzmq3
    - libzmq3-dev
before_install:
- pip install -r requirements.txt
- pip install -r requirements-test.txt
- pip install coveralls
install:
- python setup.py install
script:
- py.test
after_success:
- if [[ $TRAVIS_PYTHON_VERSION == "3.4" ]]; then coveralls; fi
before_deploy:
- pip install twine
deploy:
- provider: pypi
  user: andsor
  password:
    secure: kCUrrvDsflZPl/rBqCvYcJSD0+PVDnkfWww35/8euM4SWen8YGLsyYRqc5cDPYCMOafGquSHoJFuXOEjDC1OKajfeuULsZcFS5FXfV7HuCAKoApCyvkIWt9NJp3zNdrwHOuVsRFFWpaRQ8TC4Er4sf3aBtCJV5BW/8j7DA0D/Uq5Tv9YIm17q/l4P0ag5nhNzTdstaa5Wp/TFSWp5zXlBJx6f2ECzVmIv3XpmhLVotapdwVgUFi5YRpmZV9ShPd8c4Hc1Y8o90DIWMVCOObmPXi2GpaSwumUEMk7XPA36JS/46mVC7j56ifQ4ZkcSJBPhOPCdravsSa/zQpB0Vc0SPzLx0fhYDIttYKDxVptxJc5s0oGBP576mTFGX14NZIHF61s/9k0oHi2umZWwHPrGKxDWb+M6MYKmoulHOOLE02sE7duM6f1AdPqbxR5hVOnMH1aTkvs+57EcsO+gAo7f4+87XBuNvwkeByR0ATc408NNx/qsLv2LOXKMJLcVTS7NgNcx2kBLpUUb/wFn3x7zJlOpN7z2YMuSlrj48/7okumpnzJeC42+n8+HR00ghsoYJuaCpyTG69aOp0z1S+DU/k5hfK3NqPin4J2eY2jAT99u7GpRI4r2bsrWU0AJHUj+NCtdswsLP+raRQn8K6cGA78DEDKRUo5z6xuKSCOOAc=
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: andsor/gridjug
    python: 3.4
    branch: master
- provider: releases
  api_key:
    secure: t5th2naJawCbCBmNYOT5XySAWKhbrQdSzLmGoPNJaVD/DJOjjtW/KDSXUSijvJtAAFSBsKlBotvy7P/CKTkHCf+RcLH3J/6H5YMO1vNu8gvisF2zAXC5nbfT31rosLcttamWYWcU0+WQlYeVfJu+rtdrZoP4vvhNMCMBNQ/PLz/7YAgu+F4M2WC4L/cdQVBG7nuCK8UdHtjMlbmZVNC033jBrA+y1/e1umbbI0vJRtTTzoYNxD4pn7BmV8P1MeFyR/KSP2k5fJ78tUk47PTax2kMFijQzH68zRFTo0tywhjnzWFNFd48Lzb6pGriSyYsmAt0xUo3Z8iS4IqGSTq9q2uZgfuS+PCCvIox5FEFsqBHiTGqfdUNA96Aylw+MtnbnGAjzajuPa9giiInJLVNnUMhNk8LrPnj3dVJR5sBDIo0qQOUIbXndjbHVgQ9TaWaff5Ddehp4KbbouTgFsH49BpAyesUqkp3wcOlov6WuZXAyK6O4UldD9knDOx8Pg8mpU/8fDOiTbQItcrpp+TFkTwUbP6YvYpxxcpfFMYJOrWaLThUyh3IAWfayWuRjUBoL+bh++WfhtakmhjxduJ+/d80qKmp1e4htRNsgiTHf1wCVyRO7SCvt+iNvZHoNi3gtkSAGFflkVnXpfy4ZfWnpOIwrd0dzGiIuL9EVNfPkj8=
  on:
    tags: true
    python: 3.4
    branch: master
